### ISSUE TITLE
前端环境搭建（第二节课）

### ISSUE THREAD

**Issue by ghost** [Solidity-Chinese-Community/frontend#2]
- 介绍：本次分享主要介绍项目要使用的技术栈，及环境搭建。
  - 课程任务：技术栈介绍及环境搭建。
  - 知识要点：
    1. 解释技术栈：
      1. Node.js
      2. npm/pnpm
      3. Typescript
      4. parcel
      5. Bootstrap
      6. React
      7. Mobx
    2. 环境搭建

**Comment by ghost** [comment]
Assignees @TechQuery

**Comment by TechQuery** [comment]
https://idea2app.feishu.cn/file/boxcnu9EWmidlNXSliIqiT4VYVf
